version: "3.5"
services:
  web:
    build:
      context: ./web
    environment:
      VIRTUAL_HOST: "*.web.local"
    networks:
      - default
      - front
  back:
    build:
      context: ./back

networks:
  front:
    external: true

